### ISSUE TITLE
Error when removing `anaconda` package from `default` env-spec

### ISSUE THREAD

**Issue by koverholt** [conda/kapsel#30]
Running `conda-kapsel` version 0.3.12.

I'm trying to remove the `anaconda` package from the `default` env-spec in a newly created project where I've run `conda-kapsel init`, but I get the following error:

```
$ conda-kapsel remove-packages --env-spec default anaconda
An unexpected error occurred, most likely a bug in conda-kapsel.
    (The error was: AssertionError: )
Details about the error were saved to /var/folders/5b/1vh3qn2x7_s7mj88zc3nms0m0000gp/T/bug_details_conda-kapsel_2017-02-15_lpsov415.txt
```

The referenced log file has the following:

```
Bug details for conda-kapsel error on 2017-02-15

sys.argv: ['/Users/koverholt/anaconda3/envs/ap/bin/conda-kapsel', 'remove-packages', '--env-spec', 'default', 'anaconda']

{'version': '0.3.12'}

Traceback (most recent call last):

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/bug_handler.py", line 29, in handle_bugs
    return main_func()

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/main.py", line 307, in _main_without_bug_handler
    return _parse_args_and_run_subcommand(sys.argv)

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/main.py", line 299, in _parse_args_and_run_subcommand
    return args.main(args)

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/environment_commands.py", line 108, in main_remove_packages
    return remove_packages(args.directory, args.env_spec, args.packages)

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/environment_commands.py", line 62, in remove_packages
    return _handle_status(status, success_message)

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/environment_commands.py", line 23, in _handle_status
    console_utils.print_status_errors(status)

  File "/Users/koverholt/anaconda3/envs/ap/lib/python3.5/site-packages/conda_kapsel/commands/console_utils.py", line 29, in print_status_errors
    assert status is not None

AssertionError
```

My `kapsel.yml` currently looks like:

```
# This is an Anaconda project file.
#
# Here you can describe your project and how to run it.
# Use `conda-kapsel run` to run the project.
# The file is in YAML format, please see http://www.yaml.org/start.html for more.
#

#
# Set the 'name' key to name your project
#
name:
#
# Set the 'icon' key to give your project an icon
#
icon:
#
# In the commands section, list your runnable scripts, notebooks, and other code.
# Use `conda-kapsel add-command` to add commands.
#
commands: {}
#
# In the variables section, list any environment variables your code depends on.
# Use `conda-kapsel add-variable` to add variables.
#
variables: {}
#
# In the services section, list any services that should be
# available before your code runs.
# Use `conda-kapsel add-service` to add services.
#
services: {}
#
# In the downloads section, list any URLs to download to local files
# before your code runs.
# Use `conda-kapsel add-download` to add downloads.
#
downloads: {}
#
# In the packages section, list any packages that must be installed
# before your code runs.
# Use `conda-kapsel add-packages` to add packages.
#
packages: []
#
# In the channels section, list any Conda channel URLs to be searched
# for packages.
#
# For example,
#
# channels:
#    - https://conda.anaconda.org/asmeurer
#
channels: []
#
# You can define multiple, named environment specs.
# Each inherits any global packages or channels,
# but can have its own unique ones also.
# Use `conda-kapsel add-env-spec` to add environment specs.
#
env_specs: {default: {packages: [anaconda], channels: []}}
```

**Comment by havocp** [comment]
I believe the issue here is that you would end up with what 0.3.12 considers an invalid file, because you have a notebook command (implicitly) and you are removing the package which supplies the 'notebook' dep. Then there's a bug that throws the assertion error instead of printing out the actual error.

Made a bunch of changes today that affect this; this problem will no longer render the file invalid, and the notebook command will be explicitly in kapsel.yml also. I'll also fix it so we wouldn't hit an assertion in this case even though the exact case should no longer arise.

**Comment by koverholt** [comment]
Nice, thanks for the info and the fix!

**Comment by havocp** [comment]
This was caused by a cascade of multiple issues, all of which should now be fixed. Cross fingers.

**Comment by koverholt** [comment]
Tested with conda-kapsel 0.4.0 and things are working as expected. 👍 

The default from `conda-kapsel init` in `kapsel.yml` is:

```
env_specs: {default: {packages: [anaconda], channels: []}}
```

And after running:

```
conda-kapsel remove-packages --env-spec default anaconda
```

Results in:

```
env_specs: {default: {packages: [], channels: []}}
```

Thanks!
